|
  rebaseMergeAllowed: false
  squashMergeAllowed: true
  mergeCommitAllowed: false
  branchProtectionRules:
    - pattern: master
      isAdminEnforced: true
      requiredApprovingReviewCount: 1
      requiresCodeOwnerReviews: true
      requiresStrictStatusChecks: false
      requiredStatusCheckContexts:
        &a1
        - dependencies (8)
        - dependencies (11)
        - linkage-monitor
        - lint
        - clirr
        - units (7)
        - units (8)
        - units (11)
        - "Kokoro - Test: Integration"
        - cla/google
    - pattern: 1.3.x
      isAdminEnforced: true
      requiredApprovingReviewCount: 1
      requiresCodeOwnerReviews: true
      requiresStrictStatusChecks: false
      requiredStatusCheckContexts: *a1
  permissionRules:
    - team: yoshi-admins
      permission: admin
    - team: yoshi-java-admins
      permission: admin
    - team: yoshi-java
      permission: push
