// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/asset/v1p4beta1/asset_service.proto

package com.google.cloud.asset.v1p4beta1;

public interface ExportIamPolicyAnalysisRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.asset.v1p4beta1.ExportIamPolicyAnalysisRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The request query.
   * </pre>
   *
   * <code>.google.cloud.asset.v1p4beta1.IamPolicyAnalysisQuery analysis_query = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the analysisQuery field is set.
   */
  boolean hasAnalysisQuery();
  /**
   * <pre>
   * Required. The request query.
   * </pre>
   *
   * <code>.google.cloud.asset.v1p4beta1.IamPolicyAnalysisQuery analysis_query = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The analysisQuery.
   */
  com.google.cloud.asset.v1p4beta1.IamPolicyAnalysisQuery getAnalysisQuery();
  /**
   * <pre>
   * Required. The request query.
   * </pre>
   *
   * <code>.google.cloud.asset.v1p4beta1.IamPolicyAnalysisQuery analysis_query = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.asset.v1p4beta1.IamPolicyAnalysisQueryOrBuilder getAnalysisQueryOrBuilder();

  /**
   * <pre>
   * Optional. The request options.
   * </pre>
   *
   * <code>.google.cloud.asset.v1p4beta1.ExportIamPolicyAnalysisRequest.Options options = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the options field is set.
   */
  boolean hasOptions();
  /**
   * <pre>
   * Optional. The request options.
   * </pre>
   *
   * <code>.google.cloud.asset.v1p4beta1.ExportIamPolicyAnalysisRequest.Options options = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The options.
   */
  com.google.cloud.asset.v1p4beta1.ExportIamPolicyAnalysisRequest.Options getOptions();
  /**
   * <pre>
   * Optional. The request options.
   * </pre>
   *
   * <code>.google.cloud.asset.v1p4beta1.ExportIamPolicyAnalysisRequest.Options options = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.cloud.asset.v1p4beta1.ExportIamPolicyAnalysisRequest.OptionsOrBuilder getOptionsOrBuilder();

  /**
   * <pre>
   * Required. Output configuration indicating where the results will be output to.
   * </pre>
   *
   * <code>.google.cloud.asset.v1p4beta1.IamPolicyAnalysisOutputConfig output_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the outputConfig field is set.
   */
  boolean hasOutputConfig();
  /**
   * <pre>
   * Required. Output configuration indicating where the results will be output to.
   * </pre>
   *
   * <code>.google.cloud.asset.v1p4beta1.IamPolicyAnalysisOutputConfig output_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The outputConfig.
   */
  com.google.cloud.asset.v1p4beta1.IamPolicyAnalysisOutputConfig getOutputConfig();
  /**
   * <pre>
   * Required. Output configuration indicating where the results will be output to.
   * </pre>
   *
   * <code>.google.cloud.asset.v1p4beta1.IamPolicyAnalysisOutputConfig output_config = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.asset.v1p4beta1.IamPolicyAnalysisOutputConfigOrBuilder getOutputConfigOrBuilder();
}
