// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/asset/v1p4beta1/asset_service.proto

package com.google.cloud.asset.v1p4beta1;

public interface IamPolicyAnalysisOutputConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.asset.v1p4beta1.IamPolicyAnalysisOutputConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Destination on Cloud Storage.
   * </pre>
   *
   * <code>.google.cloud.asset.v1p4beta1.IamPolicyAnalysisOutputConfig.GcsDestination gcs_destination = 1;</code>
   * @return Whether the gcsDestination field is set.
   */
  boolean hasGcsDestination();
  /**
   * <pre>
   * Destination on Cloud Storage.
   * </pre>
   *
   * <code>.google.cloud.asset.v1p4beta1.IamPolicyAnalysisOutputConfig.GcsDestination gcs_destination = 1;</code>
   * @return The gcsDestination.
   */
  com.google.cloud.asset.v1p4beta1.IamPolicyAnalysisOutputConfig.GcsDestination getGcsDestination();
  /**
   * <pre>
   * Destination on Cloud Storage.
   * </pre>
   *
   * <code>.google.cloud.asset.v1p4beta1.IamPolicyAnalysisOutputConfig.GcsDestination gcs_destination = 1;</code>
   */
  com.google.cloud.asset.v1p4beta1.IamPolicyAnalysisOutputConfig.GcsDestinationOrBuilder getGcsDestinationOrBuilder();

  public com.google.cloud.asset.v1p4beta1.IamPolicyAnalysisOutputConfig.DestinationCase getDestinationCase();
}
