// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/asset/v1/asset_service.proto

package com.google.cloud.asset.v1;

public interface AnalyzeIamPolicyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.asset.v1.AnalyzeIamPolicyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The request query.
   * </pre>
   *
   * <code>.google.cloud.asset.v1.IamPolicyAnalysisQuery analysis_query = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the analysisQuery field is set.
   */
  boolean hasAnalysisQuery();
  /**
   * <pre>
   * Required. The request query.
   * </pre>
   *
   * <code>.google.cloud.asset.v1.IamPolicyAnalysisQuery analysis_query = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The analysisQuery.
   */
  com.google.cloud.asset.v1.IamPolicyAnalysisQuery getAnalysisQuery();
  /**
   * <pre>
   * Required. The request query.
   * </pre>
   *
   * <code>.google.cloud.asset.v1.IamPolicyAnalysisQuery analysis_query = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.asset.v1.IamPolicyAnalysisQueryOrBuilder getAnalysisQueryOrBuilder();

  /**
   * <pre>
   * Optional. Amount of time executable has to complete.  See JSON representation of
   * [Duration](https://developers.google.com/protocol-buffers/docs/proto3#json).
   * If this field is set with a value less than the RPC deadline, and the
   * execution of your query hasn't finished in the specified
   * execution timeout,  you will get a response with partial result.
   * Otherwise, your query's execution will continue until the RPC deadline.
   * If it's not finished until then, you will get a  DEADLINE_EXCEEDED error.
   * Default is empty.
   * </pre>
   *
   * <code>.google.protobuf.Duration execution_timeout = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return Whether the executionTimeout field is set.
   */
  boolean hasExecutionTimeout();
  /**
   * <pre>
   * Optional. Amount of time executable has to complete.  See JSON representation of
   * [Duration](https://developers.google.com/protocol-buffers/docs/proto3#json).
   * If this field is set with a value less than the RPC deadline, and the
   * execution of your query hasn't finished in the specified
   * execution timeout,  you will get a response with partial result.
   * Otherwise, your query's execution will continue until the RPC deadline.
   * If it's not finished until then, you will get a  DEADLINE_EXCEEDED error.
   * Default is empty.
   * </pre>
   *
   * <code>.google.protobuf.Duration execution_timeout = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The executionTimeout.
   */
  com.google.protobuf.Duration getExecutionTimeout();
  /**
   * <pre>
   * Optional. Amount of time executable has to complete.  See JSON representation of
   * [Duration](https://developers.google.com/protocol-buffers/docs/proto3#json).
   * If this field is set with a value less than the RPC deadline, and the
   * execution of your query hasn't finished in the specified
   * execution timeout,  you will get a response with partial result.
   * Otherwise, your query's execution will continue until the RPC deadline.
   * If it's not finished until then, you will get a  DEADLINE_EXCEEDED error.
   * Default is empty.
   * </pre>
   *
   * <code>.google.protobuf.Duration execution_timeout = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.protobuf.DurationOrBuilder getExecutionTimeoutOrBuilder();
}
