// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/asset/v1/asset_service.proto

package com.google.cloud.asset.v1;

public interface AnalyzeIamPolicyLongrunningRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.asset.v1.AnalyzeIamPolicyLongrunningRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The request query.
   * </pre>
   *
   * <code>.google.cloud.asset.v1.IamPolicyAnalysisQuery analysis_query = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the analysisQuery field is set.
   */
  boolean hasAnalysisQuery();
  /**
   * <pre>
   * Required. The request query.
   * </pre>
   *
   * <code>.google.cloud.asset.v1.IamPolicyAnalysisQuery analysis_query = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The analysisQuery.
   */
  com.google.cloud.asset.v1.IamPolicyAnalysisQuery getAnalysisQuery();
  /**
   * <pre>
   * Required. The request query.
   * </pre>
   *
   * <code>.google.cloud.asset.v1.IamPolicyAnalysisQuery analysis_query = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.asset.v1.IamPolicyAnalysisQueryOrBuilder getAnalysisQueryOrBuilder();

  /**
   * <pre>
   * Required. Output configuration indicating where the results will be output to.
   * </pre>
   *
   * <code>.google.cloud.asset.v1.IamPolicyAnalysisOutputConfig output_config = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the outputConfig field is set.
   */
  boolean hasOutputConfig();
  /**
   * <pre>
   * Required. Output configuration indicating where the results will be output to.
   * </pre>
   *
   * <code>.google.cloud.asset.v1.IamPolicyAnalysisOutputConfig output_config = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The outputConfig.
   */
  com.google.cloud.asset.v1.IamPolicyAnalysisOutputConfig getOutputConfig();
  /**
   * <pre>
   * Required. Output configuration indicating where the results will be output to.
   * </pre>
   *
   * <code>.google.cloud.asset.v1.IamPolicyAnalysisOutputConfig output_config = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.asset.v1.IamPolicyAnalysisOutputConfigOrBuilder getOutputConfigOrBuilder();
}
