/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/asset/v1/asset_service.proto

package com.google.cloud.asset.v1;

public final class AssetServiceProto {
  private AssetServiceProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_ExportAssetsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_ExportAssetsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_ExportAssetsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_ExportAssetsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_ListAssetsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_ListAssetsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_ListAssetsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_ListAssetsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_BatchGetAssetsHistoryRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_BatchGetAssetsHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_BatchGetAssetsHistoryResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_BatchGetAssetsHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_CreateFeedRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_CreateFeedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_GetFeedRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_GetFeedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_ListFeedsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_ListFeedsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_ListFeedsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_ListFeedsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_UpdateFeedRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_UpdateFeedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_DeleteFeedRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_DeleteFeedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_OutputConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_OutputConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_OutputResult_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_OutputResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_GcsOutputResult_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_GcsOutputResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_GcsDestination_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_GcsDestination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_BigQueryDestination_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_BigQueryDestination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_PartitionSpec_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_PartitionSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_PubsubDestination_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_PubsubDestination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_FeedOutputConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_FeedOutputConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_Feed_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_Feed_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_SearchAllResourcesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_SearchAllResourcesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_SearchAllResourcesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_SearchAllResourcesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_SearchAllIamPoliciesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_SearchAllIamPoliciesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_SearchAllIamPoliciesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_SearchAllIamPoliciesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_ResourceSelector_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_ResourceSelector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_IdentitySelector_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_IdentitySelector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_AccessSelector_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_AccessSelector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_Options_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_Options_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_ConditionContext_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_ConditionContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_AnalyzeIamPolicyRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_AnalyzeIamPolicyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_AnalyzeIamPolicyResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_AnalyzeIamPolicyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_AnalyzeIamPolicyResponse_IamPolicyAnalysis_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_AnalyzeIamPolicyResponse_IamPolicyAnalysis_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_GcsDestination_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_GcsDestination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_BigQueryDestination_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_BigQueryDestination_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_AnalyzeMoveRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_AnalyzeMoveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_AnalyzeMoveResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_AnalyzeMoveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_MoveAnalysis_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_MoveAnalysis_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_MoveAnalysisResult_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_MoveAnalysisResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_asset_v1_MoveImpact_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_asset_v1_MoveImpact_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n"
          + ")google/cloud/asset/v1/asset_service.pr"
          + "oto\022\025google.cloud.asset.v1\032\034google/api/a"
          + "nnotations.proto\032\027google/api/client.prot"
          + "o\032\037google/api/field_behavior.proto\032\031goog"
          + "le/api/resource.proto\032\"google/cloud/asse"
          + "t/v1/assets.proto\032#google/longrunning/op"
          + "erations.proto\032\036google/protobuf/duration.proto\032\033google/protobuf/empty.proto\032"
          + " google/protobuf/field_mask.proto\032\034google/protobuf/struct.proto\032\037google/protobuf/timestamp.proto\032\027google/rpc/status.proto\032\026google/type/expr.proto\"[\n"
          + "#AnalyzeIamPolicyLongrunningMetadata\0224\n"
          + "\013create_time\030\001"
          + " \001(\0132\032.google.protobuf.TimestampB\003\340A\003\"\251\002\n"
          + "\023ExportAssetsRequest\0227\n"
          + "\006parent\030\001 \001("
          + "\tB\'\340A\002\372A!\022\037cloudasset.googleapis.com/Asset\022-\n"
          + "\tread_time\030\002 \001(\0132\032.google.protobuf.Timestamp\022\023\n"
          + "\013asset_types\030\003 \003(\t\0228\n"
          + "\014content_type\030\004 \001(\0162\".google.cloud.asset.v1.ContentType\022?\n\r"
          + "output_config\030\005"
          + " \001(\0132#.google.cloud.asset.v1.OutputConfigB\003\340A\002\022\032\n"
          + "\022relationship_types\030\006 \003(\t\"\275\001\n"
          + "\024ExportAssetsResponse\022-\n"
          + "\tread_time\030\001 \001(\0132\032.google.protobuf.Timestamp\022:\n\r"
          + "output_config\030\002 \001(\0132#.google.cloud.asset.v1.OutputConfig\022:\n\r"
          + "output_result\030\003 \001(\0132#.google.cloud.asset.v1.OutputResult\"\215\002\n"
          + "\021ListAssetsRequest\0227\n"
          + "\006parent\030\001 \001("
          + "\tB\'\340A\002\372A!\022\037cloudasset.googleapis.com/Asset\022-\n"
          + "\tread_time\030\002 \001(\0132\032.google.protobuf.Timestamp\022\023\n"
          + "\013asset_types\030\003 \003(\t\0228\n"
          + "\014content_type\030\004 \001(\0162\".google.cloud.asset.v1.ContentType\022\021\n"
          + "\tpage_size\030\005 \001(\005\022\022\n\n"
          + "page_token\030\006 \001(\t\022\032\n"
          + "\022relationship_types\030\007 \003(\t\"\212\001\n"
          + "\022ListAssetsResponse\022-\n"
          + "\tread_time\030\001 \001(\0132\032.google.protobuf.Timestamp\022,\n"
          + "\006assets\030\002 \003(\0132\034.google.cloud.asset.v1.Asset\022\027\n"
          + "\017next_page_token\030\003 \001(\t\"\216\002\n"
          + "\034BatchGetAssetsHistoryRequest\0227\n"
          + "\006parent\030\001 \001("
          + "\tB\'\340A\002\372A!\022\037cloudasset.googleapis.com/Asset\022\023\n"
          + "\013asset_names\030\002 \003(\t\022=\n"
          + "\014content_type\030\003"
          + " \001(\0162\".google.cloud.asset.v1.ContentTypeB\003\340A\001\022@\n"
          + "\020read_time_window\030\004"
          + " \001(\0132!.google.cloud.asset.v1.TimeWindowB\003\340A\001\022\037\n"
          + "\022relationship_types\030\005 \003(\tB\003\340A\001\"U\n"
          + "\035BatchGetAssetsHistoryResponse\0224\n"
          + "\006assets\030\001 \003(\0132$.google.cloud.asset.v1.TemporalAsset\"n\n"
          + "\021CreateFeedRequest\022\023\n"
          + "\006parent\030\001 \001(\tB\003\340A\002\022\024\n"
          + "\007feed_id\030\002 \001(\tB\003\340A\002\022.\n"
          + "\004feed\030\003 \001(\0132\033.google.cloud.asset.v1.FeedB\003\340A\002\"F\n"
          + "\016GetFeedRequest\0224\n"
          + "\004name\030\001 \001(\tB&\340A\002\372A \n"
          + "\036cloudasset.googleapis.com/Feed\"\'\n"
          + "\020ListFeedsRequest\022\023\n"
          + "\006parent\030\001 \001(\tB\003\340A\002\"?\n"
          + "\021ListFeedsResponse\022*\n"
          + "\005feeds\030\001 \003(\0132\033.google.cloud.asset.v1.Feed\"y\n"
          + "\021UpdateFeedRequest\022.\n"
          + "\004feed\030\001 \001(\0132\033.google.cloud.asset.v1.FeedB\003\340A\002\0224\n"
          + "\013update_mask\030\002 \001(\0132\032.google.protobuf.FieldMaskB\003\340A\002\"I\n"
          + "\021DeleteFeedRequest\0224\n"
          + "\004name\030\001 \001(\tB&\340A\002\372A \n"
          + "\036cloudasset.googleapis.com/Feed\"\253\001\n"
          + "\014OutputConfig\022@\n"
          + "\017gcs_destination\030\001"
          + " \001(\0132%.google.cloud.asset.v1.GcsDestinationH\000\022J\n"
          + "\024bigquery_destination\030\002"
          + " \001(\0132*.google.cloud.asset.v1.BigQueryDestinationH\000B\r\n"
          + "\013destination\"V\n"
          + "\014OutputResult\022<\n\n"
          + "gcs_result\030\001 \001(\0132&.google.cloud.asset.v1.GcsOutputResultH\000B\010\n"
          + "\006result\"\037\n"
          + "\017GcsOutputResult\022\014\n"
          + "\004uris\030\001 \003(\t\"C\n"
          + "\016GcsDestination\022\r\n"
          + "\003uri\030\001 \001(\tH\000\022\024\n\n"
          + "uri_prefix\030\002 \001(\tH\000B\014\n\n"
          + "object_uri\"\264\001\n"
          + "\023BigQueryDestination\022\024\n"
          + "\007dataset\030\001 \001(\tB\003\340A\002\022\022\n"
          + "\005table\030\002 \001(\tB\003\340A\002\022\r\n"
          + "\005force\030\003 \001(\010\022<\n"
          + "\016partition_spec\030\004 \001(\0132$.google.cloud.asset.v1.PartitionSpec\022&\n"
          + "\036separate_tables_per_asset_type\030\005 \001(\010\"\251\001\n\r"
          + "PartitionSpec\022H\n\r"
          + "partition_key\030\001"
          + " \001(\01621.google.cloud.asset.v1.PartitionSpec.PartitionKey\"N\n"
          + "\014PartitionKey\022\035\n"
          + "\031PARTITION_KEY_UNSPECIFIED\020\000\022\r\n"
          + "\tREAD_TIME\020\001\022\020\n"
          + "\014REQUEST_TIME\020\002\"\"\n"
          + "\021PubsubDestination\022\r\n"
          + "\005topic\030\001 \001(\t\"i\n"
          + "\020FeedOutputConfig\022F\n"
          + "\022pubsub_destination\030\001"
          + " \001(\0132(.google.cloud.asset.v1.PubsubDestinationH\000B\r\n"
          + "\013destination\"\235\003\n"
          + "\004Feed\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\002\022\023\n"
          + "\013asset_names\030\002 \003(\t\022\023\n"
          + "\013asset_types\030\003 \003(\t\0228\n"
          + "\014content_type\030\004 \001(\0162\".google.cloud.asset.v1.ContentType\022H\n"
          + "\022feed_output_config\030\005"
          + " \001(\0132\'.google.cloud.asset.v1.FeedOutputConfigB\003\340A\002\022$\n"
          + "\tcondition\030\006 \001(\0132\021.google.type.Expr\022\032\n"
          + "\022relationship_types\030\007 \003(\t:\221\001\352A\215\001\n"
          + "\036cloudasset.googleapis.com/Feed\022\037pr"
          + "ojects/{project}/feeds/{feed}\022\035folders/{folder}/feeds/{feed}\022)organizations/{organization}/feeds/{feed}"
          + " \001\"\331\001\n"
          + "\031SearchAllResourcesRequest\022\022\n"
          + "\005scope\030\001 \001(\tB\003\340A\002\022\022\n"
          + "\005query\030\002 \001(\tB\003\340A\001\022\030\n"
          + "\013asset_types\030\003 \003(\tB\003\340A\001\022\026\n"
          + "\tpage_size\030\004 \001(\005B\003\340A\001\022\027\n\n"
          + "page_token\030\005 \001(\tB\003\340A\001\022\025\n"
          + "\010order_by\030\006 \001(\tB\003\340A\001\0222\n"
          + "\tread_mask\030\010 \001(\0132\032.google.protobuf.FieldMaskB\003\340A\001\"s\n"
          + "\032SearchAllResourcesResponse\022<\n"
          + "\007results\030\001 \003(\0132+.google.cloud.asset.v1.ResourceSearchResult\022\027\n"
          + "\017next_page_token\030\002 \001(\t\"\247\001\n"
          + "\033SearchAllIamPoliciesRequest\022\022\n"
          + "\005scope\030\001 \001(\tB\003\340A\002\022\022\n"
          + "\005query\030\002 \001(\tB\003\340A\001\022\026\n"
          + "\tpage_size\030\003 \001(\005B\003\340A\001\022\027\n\n"
          + "page_token\030\004 \001(\tB\003\340A\001\022\030\n"
          + "\013asset_types\030\005 \003(\tB\003\340A\001\022\025\n"
          + "\010order_by\030\007 \001(\tB\003\340A\001\"v\n"
          + "\034SearchAllIamPoliciesResponse\022=\n"
          + "\007results\030\001 \003(\0132,.google.cloud.asset.v1.IamPolicySearchResult\022\027\n"
          + "\017next_page_token\030\002 \001(\t\"\306\007\n"
          + "\026IamPolicyAnalysisQuery\022\022\n"
          + "\005scope\030\001 \001(\tB\003\340A\002\022^\n"
          + "\021resource_selector\030\002"
          + " \001(\0132>.google.cloud.asset.v1.IamPolicyAnalysisQuery.ResourceSelectorB\003\340A\001\022^\n"
          + "\021identity_selector\030\003"
          + " \001(\0132>.google.cloud.asset.v1.IamPolicyAnalysisQuery.IdentitySelectorB\003\340A\001\022Z\n"
          + "\017access_selector\030\004"
          + " \001(\0132<.google.cloud.asset.v1.IamPolicyAnalysisQuery.AccessSelectorB\003\340A\001\022K\n"
          + "\007options\030\005"
          + " \001(\01325.google.cloud.asset.v1.IamPolicyAnalysisQuery.OptionsB\003\340A\001\022^\n"
          + "\021condition_context\030\006"
          + " \001(\0132>.google.cloud.asset.v1.IamPolicyAnalysisQuery.ConditionContextB\003\340A\001\0323\n"
          + "\020ResourceSelector\022\037\n"
          + "\022full_resource_name\030\001 \001(\tB\003\340A\002\032)\n"
          + "\020IdentitySelector\022\025\n"
          + "\010identity\030\001 \001(\tB\003\340A\002\032>\n"
          + "\016AccessSelector\022\022\n"
          + "\005roles\030\001 \003(\tB\003\340A\001\022\030\n"
          + "\013permissions\030\002 \003(\tB\003\340A\001\032\330\001\n"
          + "\007Options\022\032\n\r"
          + "expand_groups\030\001 \001(\010B\003\340A\001\022\031\n"
          + "\014expand_roles\030\002 \001(\010B\003\340A\001\022\035\n"
          + "\020expand_resources\030\003 \001(\010B\003\340A\001\022\"\n"
          + "\025output_resource_edges\030\004 \001(\010B\003\340A\001\022\037\n"
          + "\022output_group_edges\030\005 \001(\010B\003\340A\001\0222\n"
          + "%analyze_service_account_impersonation\030\006 \001(\010B\003\340A\001\032T\n"
          + "\020ConditionContext\0221\n"
          + "\013access_time\030\001 \001(\0132\032.google.protobuf.TimestampH\000B\r\n"
          + "\013TimeContext\"\240\001\n"
          + "\027AnalyzeIamPolicyRequest\022J\n"
          + "\016analysis_query\030\001"
          + " \001(\0132-.google.cloud.asset.v1.IamPolicyAnalysisQueryB\003\340A\002\0229\n"
          + "\021execution_timeout\030\002"
          + " \001(\0132\031.google.protobuf.DurationB\003\340A\001\"\212\004\n"
          + "\030AnalyzeIamPolicyResponse\022X\n\r"
          + "main_analysis\030\001"
          + " \001(\0132A.google.cloud.asset.v1.AnalyzeIamPolicyResponse.IamPolicyAnalysis\022q\n"
          + "&service_account_impersonation_analysis\030\002"
          + " \003(\0132A.google.cloud.asset.v1.AnalyzeIamPolicyResponse.IamPolicyAnalysis\022\026\n"
          + "\016fully_explored\030\003 \001(\010\032\210\002\n"
          + "\021IamPolicyAnalysis\022E\n"
          + "\016analysis_query\030\001"
          + " \001(\0132-.google.cloud.asset.v1.IamPolicyAnalysisQuery\022H\n"
          + "\020analysis_results\030\002"
          + " \003(\0132..google.cloud.asset.v1.IamPolicyAnalysisResult\022\026\n"
          + "\016fully_explored\030\003 \001(\010\022J\n"
          + "\023non_critical_errors\030\005"
          + " \003(\0132-.google.cloud.asset.v1.IamPolicyAnalysisState\"\264\004\n"
          + "\035IamPolicyAnalysisOutputConfig\022^\n"
          + "\017gcs_destination\030\001"
          + " \001(\0132C.google.cloud.asset.v1.IamPolicyAnalysisOutputConfig.GcsDestinationH\000\022h\n"
          + "\024bigquery_destination\030\002"
          + " \001(\0132H.google.cloud.asset.v1.IamPolicyAnalysisOutputConfig.BigQueryDestinationH\000\032\"\n"
          + "\016GcsDestination\022\020\n"
          + "\003uri\030\001 \001(\tB\003\340A\002\032\225\002\n"
          + "\023BigQueryDestination\022\024\n"
          + "\007dataset\030\001 \001(\tB\003\340A\002\022\031\n"
          + "\014table_prefix\030\002 \001(\tB\003\340A\002\022l\n\r"
          + "partition_key\030\003"
          + " \001(\0162U.google.cloud.asset.v1.IamPolicyAnalysisOutputConfig.BigQueryDestination.PartitionKey\022\036\n"
          + "\021write_disposition\030\004 \001(\tB\003\340A\001\"?\n"
          + "\014PartitionKey\022\035\n"
          + "\031PARTITION_KEY_UNSPECIFIED\020\000\022\020\n"
          + "\014REQUEST_TIME\020\001B\r\n"
          + "\013destination\"\302\001\n"
          + "\"AnalyzeIamPolicyLongrunningRequest\022J\n"
          + "\016analysis_query\030\001"
          + " \001(\0132-.google.cloud.asset.v1.IamPolicyAnalysisQueryB\003\340A\002\022P\n\r"
          + "output_config\030\002"
          + " \001(\01324.google.cloud.asset.v1.IamPolicyAnalysisOutputConfigB\003\340A\002\"%\n"
          + "#AnalyzeIamPolicyLongrunningResponse\"\326\001\n"
          + "\022AnalyzeMoveRequest\022\025\n"
          + "\010resource\030\001 \001(\tB\003\340A\002\022\037\n"
          + "\022destination_parent\030\002 \001(\tB\003\340A\002\022D\n"
          + "\004view\030\003"
          + " \001(\01626.google.cloud.asset.v1.AnalyzeMoveRequest.AnalysisView\"B\n"
          + "\014AnalysisView\022\035\n"
          + "\031ANALYSIS_VIEW_UNSPECIFIED\020\000\022\010\n"
          + "\004FULL\020\001\022\t\n"
          + "\005BASIC\020\002\"Q\n"
          + "\023AnalyzeMoveResponse\022:\n\r"
          + "move_analysis\030\001 \003(\0132#.google.cloud.asset.v1.MoveAnalysis\"\222\001\n"
          + "\014MoveAnalysis\022\024\n"
          + "\014display_name\030\001 \001(\t\022=\n"
          + "\010analysis\030\002 \001(\0132).google.cloud.asset.v1.MoveAnalysisResultH\000\022#\n"
          + "\005error\030\003 \001(\0132\022.google.rpc.StatusH\000B\010\n"
          + "\006result\"~\n"
          + "\022MoveAnalysisResult\0223\n"
          + "\010blockers\030\001 \003(\0132!.google.cloud.asset.v1.MoveImpact\0223\n"
          + "\010warnings\030\002 \003(\0132!.google.cloud.asset.v1.MoveImpact\"\034\n\n"
          + "MoveImpact\022\016\n"
          + "\006detail\030\001 \001(\t*\220\001\n"
          + "\013ContentType\022\034\n"
          + "\030CONTENT_TYPE_UNSPECIFIED\020\000\022\014\n"
          + "\010RESOURCE\020\001\022\016\n\n"
          + "IAM_POLICY\020\002\022\016\n\n"
          + "ORG_POLICY\020\004\022\021\n\r"
          + "ACCESS_POLICY\020\005\022\020\n"
          + "\014OS_INVENTORY\020\006\022\020\n"
          + "\014RELATIONSHIP\020\0072\367\021\n"
          + "\014AssetService\022\336\001\n"
          + "\014ExportAssets\022*.google.cloud.asset.v1.ExportAssetsRequest\032\035.google.longrunning.Operation\"\202\001\202\323\344\223\002\"\"\035/v1/{parent=*/*}:exportAssets:\001*\312AW\n"
          + "*google.cloud.asset.v1.ExportAssetsResponse\022)google.cloud.asset.v1.ExportAssetsRequest\022\213\001\n\n"
          + "ListAssets\022(.google.cloud.asset.v1.ListAssetsRequest\032).google.cloud.asset.v1.ListAssetsResponse\"(\202\323\344\223\002\031\022\027/v1/{parent=*/*}/assets\332A\006parent\022\262\001\n"
          + "\025BatchGetAssetsHistory\0223.google.cloud.asset.v1.BatchGetAssetsHistoryRequest\0324.google.cloud.asset.v1.BatchGetAssetsHistoryResponse\".\202\323\344\223\002(\022&/v1/{parent=*/*}:batchGetAssetsHistory\022\177\n\n"
          + "CreateFeed\022(.google.cloud.asset.v1.CreateFeedRequest\032\033.google.cloud.asset.v1.Feed\"*\202\323\344\223\002\033\"\026/v1/{parent=*/*}/feeds:\001*\332A\006parent\022t\n"
          + "\007GetFeed\022%.google.cloud.asset.v1.GetFeedRequest\032\033.google.cloud.asset.v1.Feed\"%\202\323\344\223\002\030\022\026/v1/{name=*/*/feeds/*}\332A\004name\022\207\001\n"
          + "\tListFeeds\022\'.google.cloud.asset.v1.ListFeedsRequest\032(.google.cloud.asset.v1.ListFeedsResponse\"\'\202\323\344\223\002\030\022\026/v1/{parent=*/*}/feeds\332A\006parent\022\202\001\n\n"
          + "UpdateFeed\022(.google"
          + ".cloud.asset.v1.UpdateFeedRequest\032\033.google.cloud.asset.v1.Feed\"-\202\323\344\223\002"
          + " 2\033/v1/{feed.name=*/*/feeds/*}:\001*\332A\004feed\022u\n\n"
          + "DeleteFeed\022(.google.cloud.asset.v1.DeleteFeedRequest\032\026.google.protobuf.Empty\"%\202\323\344\223\002\030*\026/v1/{name=*/*/feeds/*}\332A\004name\022\277\001\n"
          + "\022SearchAllResources\0220.google.cloud.asset.v1.Sear"
          + "chAllResourcesRequest\0321.google.cloud.asset.v1.SearchAllResourcesResponse\"D\202\323\344\223\002$\022\"/v1/{scope=*/*}:searchAllResources\332A\027scope,query,asset_types\022\273\001\n"
          + "\024SearchAllIamPolicies\0222.google.cloud.asset.v1.SearchAl"
          + "lIamPoliciesRequest\0323.google.cloud.asset.v1.SearchAllIamPoliciesResponse\":\202\323\344\223\002&\022$/v1/{scope=*/*}:searchAllIamPolicies\332A\013scope,query\022\254\001\n"
          + "\020AnalyzeIamPolicy\022..google.cloud.asset.v1.AnalyzeIamPolicyRequest\032/.google.cloud.asset.v1.AnalyzeIamPolicyResponse\"7\202\323\344\223\0021\022//v1/{analysis_query.scope=*/*}:analyzeIamPolicy\022\270\002\n"
          + "\033AnalyzeIamPolicyLongrunning\0229.google.cloud.asset"
          + ".v1.AnalyzeIamPolicyLongrunningRequest\032\035.google.longrunning.Operation\"\276\001\202\323\344\223\002?\":/v1/{analysis_query.scope=*/*}:analyzeIamPolicyLongrunning:\001*\312Av\n"
          + "9google.cloud.asset.v1.AnalyzeIamPolicyLongrunningResponse\0229google.cloud.asset.v1.AnalyzeIamPolicyLongrunningMetadata\022\214\001\n"
          + "\013AnalyzeMove\022).google.cloud.asset.v1.AnalyzeMoveReques"
          + "t\032*.google.cloud.asset.v1.AnalyzeMoveResponse\"&\202\323\344\223\002"
          + " \022\036/v1/{resource=*/*}:analyzeMove\032M\312A\031cloudasset.googleapis.com\322A.https://www.googleapis.com/auth/cloud-platformB\234\001\n"
          + "\031com.google.cloud.asset.v1B\021AssetServiceProtoP\001Z:google.golang.org/genpr"
          + "oto/googleapis/cloud/asset/v1;asset\252\002\025Go"
          + "ogle.Cloud.Asset.V1\312\002\025Google\\Cloud\\Asset\\V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.cloud.asset.v1.AssetProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.DurationProto.getDescriptor(),
              com.google.protobuf.EmptyProto.getDescriptor(),
              com.google.protobuf.FieldMaskProto.getDescriptor(),
              com.google.protobuf.StructProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.rpc.StatusProto.getDescriptor(),
              com.google.type.ExprProto.getDescriptor(),
            });
    internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningMetadata_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningMetadata_descriptor,
            new java.lang.String[] {
              "CreateTime",
            });
    internal_static_google_cloud_asset_v1_ExportAssetsRequest_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_asset_v1_ExportAssetsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_ExportAssetsRequest_descriptor,
            new java.lang.String[] {
              "Parent",
              "ReadTime",
              "AssetTypes",
              "ContentType",
              "OutputConfig",
              "RelationshipTypes",
            });
    internal_static_google_cloud_asset_v1_ExportAssetsResponse_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_asset_v1_ExportAssetsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_ExportAssetsResponse_descriptor,
            new java.lang.String[] {
              "ReadTime", "OutputConfig", "OutputResult",
            });
    internal_static_google_cloud_asset_v1_ListAssetsRequest_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_asset_v1_ListAssetsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_ListAssetsRequest_descriptor,
            new java.lang.String[] {
              "Parent",
              "ReadTime",
              "AssetTypes",
              "ContentType",
              "PageSize",
              "PageToken",
              "RelationshipTypes",
            });
    internal_static_google_cloud_asset_v1_ListAssetsResponse_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_asset_v1_ListAssetsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_ListAssetsResponse_descriptor,
            new java.lang.String[] {
              "ReadTime", "Assets", "NextPageToken",
            });
    internal_static_google_cloud_asset_v1_BatchGetAssetsHistoryRequest_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_asset_v1_BatchGetAssetsHistoryRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_BatchGetAssetsHistoryRequest_descriptor,
            new java.lang.String[] {
              "Parent", "AssetNames", "ContentType", "ReadTimeWindow", "RelationshipTypes",
            });
    internal_static_google_cloud_asset_v1_BatchGetAssetsHistoryResponse_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_asset_v1_BatchGetAssetsHistoryResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_BatchGetAssetsHistoryResponse_descriptor,
            new java.lang.String[] {
              "Assets",
            });
    internal_static_google_cloud_asset_v1_CreateFeedRequest_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_asset_v1_CreateFeedRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_CreateFeedRequest_descriptor,
            new java.lang.String[] {
              "Parent", "FeedId", "Feed",
            });
    internal_static_google_cloud_asset_v1_GetFeedRequest_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_asset_v1_GetFeedRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_GetFeedRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_asset_v1_ListFeedsRequest_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_asset_v1_ListFeedsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_ListFeedsRequest_descriptor,
            new java.lang.String[] {
              "Parent",
            });
    internal_static_google_cloud_asset_v1_ListFeedsResponse_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_asset_v1_ListFeedsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_ListFeedsResponse_descriptor,
            new java.lang.String[] {
              "Feeds",
            });
    internal_static_google_cloud_asset_v1_UpdateFeedRequest_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_asset_v1_UpdateFeedRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_UpdateFeedRequest_descriptor,
            new java.lang.String[] {
              "Feed", "UpdateMask",
            });
    internal_static_google_cloud_asset_v1_DeleteFeedRequest_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_asset_v1_DeleteFeedRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_DeleteFeedRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_asset_v1_OutputConfig_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_asset_v1_OutputConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_OutputConfig_descriptor,
            new java.lang.String[] {
              "GcsDestination", "BigqueryDestination", "Destination",
            });
    internal_static_google_cloud_asset_v1_OutputResult_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_asset_v1_OutputResult_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_OutputResult_descriptor,
            new java.lang.String[] {
              "GcsResult", "Result",
            });
    internal_static_google_cloud_asset_v1_GcsOutputResult_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_asset_v1_GcsOutputResult_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_GcsOutputResult_descriptor,
            new java.lang.String[] {
              "Uris",
            });
    internal_static_google_cloud_asset_v1_GcsDestination_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_asset_v1_GcsDestination_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_GcsDestination_descriptor,
            new java.lang.String[] {
              "Uri", "UriPrefix", "ObjectUri",
            });
    internal_static_google_cloud_asset_v1_BigQueryDestination_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_asset_v1_BigQueryDestination_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_BigQueryDestination_descriptor,
            new java.lang.String[] {
              "Dataset", "Table", "Force", "PartitionSpec", "SeparateTablesPerAssetType",
            });
    internal_static_google_cloud_asset_v1_PartitionSpec_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_cloud_asset_v1_PartitionSpec_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_PartitionSpec_descriptor,
            new java.lang.String[] {
              "PartitionKey",
            });
    internal_static_google_cloud_asset_v1_PubsubDestination_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_cloud_asset_v1_PubsubDestination_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_PubsubDestination_descriptor,
            new java.lang.String[] {
              "Topic",
            });
    internal_static_google_cloud_asset_v1_FeedOutputConfig_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_cloud_asset_v1_FeedOutputConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_FeedOutputConfig_descriptor,
            new java.lang.String[] {
              "PubsubDestination", "Destination",
            });
    internal_static_google_cloud_asset_v1_Feed_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_cloud_asset_v1_Feed_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_Feed_descriptor,
            new java.lang.String[] {
              "Name",
              "AssetNames",
              "AssetTypes",
              "ContentType",
              "FeedOutputConfig",
              "Condition",
              "RelationshipTypes",
            });
    internal_static_google_cloud_asset_v1_SearchAllResourcesRequest_descriptor =
        getDescriptor().getMessageTypes().get(22);
    internal_static_google_cloud_asset_v1_SearchAllResourcesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_SearchAllResourcesRequest_descriptor,
            new java.lang.String[] {
              "Scope", "Query", "AssetTypes", "PageSize", "PageToken", "OrderBy", "ReadMask",
            });
    internal_static_google_cloud_asset_v1_SearchAllResourcesResponse_descriptor =
        getDescriptor().getMessageTypes().get(23);
    internal_static_google_cloud_asset_v1_SearchAllResourcesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_SearchAllResourcesResponse_descriptor,
            new java.lang.String[] {
              "Results", "NextPageToken",
            });
    internal_static_google_cloud_asset_v1_SearchAllIamPoliciesRequest_descriptor =
        getDescriptor().getMessageTypes().get(24);
    internal_static_google_cloud_asset_v1_SearchAllIamPoliciesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_SearchAllIamPoliciesRequest_descriptor,
            new java.lang.String[] {
              "Scope", "Query", "PageSize", "PageToken", "AssetTypes", "OrderBy",
            });
    internal_static_google_cloud_asset_v1_SearchAllIamPoliciesResponse_descriptor =
        getDescriptor().getMessageTypes().get(25);
    internal_static_google_cloud_asset_v1_SearchAllIamPoliciesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_SearchAllIamPoliciesResponse_descriptor,
            new java.lang.String[] {
              "Results", "NextPageToken",
            });
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_descriptor =
        getDescriptor().getMessageTypes().get(26);
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_descriptor,
            new java.lang.String[] {
              "Scope",
              "ResourceSelector",
              "IdentitySelector",
              "AccessSelector",
              "Options",
              "ConditionContext",
            });
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_ResourceSelector_descriptor =
        internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_ResourceSelector_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_ResourceSelector_descriptor,
            new java.lang.String[] {
              "FullResourceName",
            });
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_IdentitySelector_descriptor =
        internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_IdentitySelector_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_IdentitySelector_descriptor,
            new java.lang.String[] {
              "Identity",
            });
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_AccessSelector_descriptor =
        internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_descriptor
            .getNestedTypes()
            .get(2);
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_AccessSelector_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_AccessSelector_descriptor,
            new java.lang.String[] {
              "Roles", "Permissions",
            });
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_Options_descriptor =
        internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_descriptor
            .getNestedTypes()
            .get(3);
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_Options_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_Options_descriptor,
            new java.lang.String[] {
              "ExpandGroups",
              "ExpandRoles",
              "ExpandResources",
              "OutputResourceEdges",
              "OutputGroupEdges",
              "AnalyzeServiceAccountImpersonation",
            });
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_ConditionContext_descriptor =
        internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_descriptor
            .getNestedTypes()
            .get(4);
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_ConditionContext_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_IamPolicyAnalysisQuery_ConditionContext_descriptor,
            new java.lang.String[] {
              "AccessTime", "TimeContext",
            });
    internal_static_google_cloud_asset_v1_AnalyzeIamPolicyRequest_descriptor =
        getDescriptor().getMessageTypes().get(27);
    internal_static_google_cloud_asset_v1_AnalyzeIamPolicyRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_AnalyzeIamPolicyRequest_descriptor,
            new java.lang.String[] {
              "AnalysisQuery", "ExecutionTimeout",
            });
    internal_static_google_cloud_asset_v1_AnalyzeIamPolicyResponse_descriptor =
        getDescriptor().getMessageTypes().get(28);
    internal_static_google_cloud_asset_v1_AnalyzeIamPolicyResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_AnalyzeIamPolicyResponse_descriptor,
            new java.lang.String[] {
              "MainAnalysis", "ServiceAccountImpersonationAnalysis", "FullyExplored",
            });
    internal_static_google_cloud_asset_v1_AnalyzeIamPolicyResponse_IamPolicyAnalysis_descriptor =
        internal_static_google_cloud_asset_v1_AnalyzeIamPolicyResponse_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_asset_v1_AnalyzeIamPolicyResponse_IamPolicyAnalysis_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_AnalyzeIamPolicyResponse_IamPolicyAnalysis_descriptor,
            new java.lang.String[] {
              "AnalysisQuery", "AnalysisResults", "FullyExplored", "NonCriticalErrors",
            });
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_descriptor =
        getDescriptor().getMessageTypes().get(29);
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_descriptor,
            new java.lang.String[] {
              "GcsDestination", "BigqueryDestination", "Destination",
            });
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_GcsDestination_descriptor =
        internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_GcsDestination_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_GcsDestination_descriptor,
            new java.lang.String[] {
              "Uri",
            });
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_BigQueryDestination_descriptor =
        internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_BigQueryDestination_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_IamPolicyAnalysisOutputConfig_BigQueryDestination_descriptor,
            new java.lang.String[] {
              "Dataset", "TablePrefix", "PartitionKey", "WriteDisposition",
            });
    internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningRequest_descriptor =
        getDescriptor().getMessageTypes().get(30);
    internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningRequest_descriptor,
            new java.lang.String[] {
              "AnalysisQuery", "OutputConfig",
            });
    internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningResponse_descriptor =
        getDescriptor().getMessageTypes().get(31);
    internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_AnalyzeIamPolicyLongrunningResponse_descriptor,
            new java.lang.String[] {});
    internal_static_google_cloud_asset_v1_AnalyzeMoveRequest_descriptor =
        getDescriptor().getMessageTypes().get(32);
    internal_static_google_cloud_asset_v1_AnalyzeMoveRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_AnalyzeMoveRequest_descriptor,
            new java.lang.String[] {
              "Resource", "DestinationParent", "View",
            });
    internal_static_google_cloud_asset_v1_AnalyzeMoveResponse_descriptor =
        getDescriptor().getMessageTypes().get(33);
    internal_static_google_cloud_asset_v1_AnalyzeMoveResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_AnalyzeMoveResponse_descriptor,
            new java.lang.String[] {
              "MoveAnalysis",
            });
    internal_static_google_cloud_asset_v1_MoveAnalysis_descriptor =
        getDescriptor().getMessageTypes().get(34);
    internal_static_google_cloud_asset_v1_MoveAnalysis_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_MoveAnalysis_descriptor,
            new java.lang.String[] {
              "DisplayName", "Analysis", "Error", "Result",
            });
    internal_static_google_cloud_asset_v1_MoveAnalysisResult_descriptor =
        getDescriptor().getMessageTypes().get(35);
    internal_static_google_cloud_asset_v1_MoveAnalysisResult_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_MoveAnalysisResult_descriptor,
            new java.lang.String[] {
              "Blockers", "Warnings",
            });
    internal_static_google_cloud_asset_v1_MoveImpact_descriptor =
        getDescriptor().getMessageTypes().get(36);
    internal_static_google_cloud_asset_v1_MoveImpact_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_asset_v1_MoveImpact_descriptor,
            new java.lang.String[] {
              "Detail",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.asset.v1.AssetProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
    com.google.type.ExprProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
