on:
  pull_request:
name: auto-merge-readme
jobs:
  approve:
    runs-on: ubuntu-latest
    if: github.repository_owner == "googleapis" && github.head_ref == "autosynth-readme"
    steps:
      - uses: actions/github-script@v3.0.0
        with:
          github-token: ${{secrets.YOSHI_APPROVER_TOKEN}}
          debug: true
          script: |
            // only approve PRs from yoshi-automation
            if (context.payload.pull_request.user.login !== "yoshi-automation") {
              return;
            }

            // only approve PRs like "chore: release <release version>"
            if ( !context.payload.pull_request.title === "chore: regenerate README") ) {
              return;
            }

            // only approve PRs with README.md and synth.metadata changes
            const files = new Set((await github.pulls.listFiles.endpoint({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            })).data.map(file => file.filename));
            if (files.size != 2 || !files.has("README.md") || !files.has("synth.metadata")) {
              return;
            }

            // approve release PR
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Rubber stamped release!',
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            });

            // attach kokoro:force-run and automerge labels
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['automerge']
            });
